version: '3'
services:
  mysql:
    image: mysql:5.7
    container_name: library-database
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 'root'

  mailcatcher:
    image: schickling/mailcatcher
    container_name: library-mailserver
    ports:
      - "1080:1080"
      - "1025:1025"